name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
    branches: [ main, develop ]
  pull_request:
    paths:
      - 'backend/**'
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f backend/api/requirements.txt ]; then pip install -r backend/api/requirements.txt; fi
        pip install pytest pytest-cov flake8
    - name: Lint with flake8
      run: |
        flake8 backend/api/src
    - name: Test with pytest
      run: |
        pytest backend/api/test --cov=backend/api/src
