on:
push:
paths:
- 'frontend/web/'
branches: [ main, develop ]
pull_request:
paths:
- 'frontend/web/'
branches: [ main, develop ]
jobs:
test:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v3
- name: Set up Node.js
uses: actions/setup-node@v3
with:
node-version: 16
- name: Install dependencies
run: |
cd frontend/web
npm ci
- name: Run linting
run: |
cd frontend/web
npm run lint
- name: Run tests
run: |
cd frontend/web
npm test
" > .github/workflows/frontend-web-ci.yml
